location /levantamiento/ {
    rewrite ^/levantamiento/?(.*)$ /$1 break;

    proxy_pass http://levantamiento:3000;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

    # 🔥 tolerancia a upstream inexistente
    proxy_connect_timeout 1s;
    proxy_read_timeout 5s;
    proxy_next_upstream error timeout http_502 http_503 http_504;

    # 🔥 interceptar error y no romper
    proxy_intercept_errors on;
    error_page 502 503 504 =404 /levantamiento_not_available;
}

location = /levantamiento_not_available {
    return 404;
}